"use client"

import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import { Header } from "@/components/layout/header"
import { Footer } from "@/components/layout/footer"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Sparkles, Loader2, Image as ImageIcon, CheckCircle2 } from "lucide-react"
import { toast } from "sonner"
import { supabase } from "@/lib/supabase"
import { categories } from "@/lib/blog-data"

export default function CreateBlogPage() {
    const router = useRouter()
    const [user, setUser] = useState<any>(null)
    const [isLoading, setIsLoading] = useState(false)
    const [isGenerating, setIsGenerating] = useState(false)

    const [formData, setFormData] = useState({
        title: "",
        topic: "",
        category: "Rental Tips",
        content: "",
        excerpt: "",
        cover_image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=2000&auto=format&fit=crop"
    })

    useEffect(() => {
        const checkUser = async () => {
            const { data: { session } } = await supabase.auth.getSession()
            if (!session) {
                toast.error("Please log in to create a blog post")
                router.push("/login")
            } else {
                setUser(session.user)
            }
        }
        checkUser()
    }, [router])

    const handleGenerate = async () => {
        if (!formData.title && !formData.topic) {
            toast.error("Please provide a title or topic first")
            return
        }

        setIsGenerating(true)
        try {
            const response = await fetch("/api/blog/generate", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    title: formData.title,
                    topic: formData.topic,
                    category: formData.category
                }),
            })

            if (!response.ok) throw new Error("AI generation failed")

            const data = await response.json()
            setFormData(prev => ({
                ...prev,
                title: data.title || prev.title,
                content: data.content,
                excerpt: data.excerpt,
                cover_image: data.cover_image || prev.cover_image,
            }))
            toast.success("Blog content & image generated by Gemini!")
        } catch (error) {
            console.error(error)
            toast.error("Failed to generate content. Please try again.")
        } finally {
            setIsGenerating(false)
        }
    }

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault()
        if (!user) return

        setIsLoading(true)
        try {
            const response = await fetch("/api/blog", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    ...formData,
                    author_id: user.id,
                    author_name: user.user_metadata?.full_name || "Leli User",
                    author_avatar: user.user_metadata?.avatar_url || "/logo.png",
                    author_role: "Community Member",
                    reading_time: `${Math.ceil(formData.content.split(' ').length / 200)} min read`
                }),
            })

            if (!response.ok) throw new Error("Failed to publish blog")

            const data = await response.json()
            toast.success("Blog post published successfully!")
            router.push("/blog")
        } catch (error) {
            console.error(error)
            toast.error("Failed to publish blog. Please try again.")
        } finally {
            setIsLoading(false)
        }
    }

    if (!user) return null

    return (
        <div className="min-h-screen flex flex-col bg-background">
            <Header />
            <main className="flex-1 pt-24 pb-16 px-4">
                <div className="container mx-auto max-w-4xl">
                    <div className="mb-8">
                        <h1 className="text-3xl font-extrabold tracking-tight">Create a <span className="text-primary">New Blog Post</span></h1>
                        <p className="text-muted-foreground">Share your insights and tips with the Leli Rentals community.</p>
                    </div>

                    <form onSubmit={handleSubmit} className="space-y-8">
                        <Card className="glass-card border-primary/10 overflow-hidden rounded-3xl">
                            <CardHeader className="bg-primary/5 border-b">
                                <CardTitle className="flex items-center gap-2">
                                    <Sparkles className="h-5 w-5 text-primary" />
                                    AI Assistance
                                </CardTitle>
                                <CardDescription>
                                    Need help with your content? Let Gemini generate a draft for you.
                                </CardDescription>
                            </CardHeader>
                            <CardContent className="pt-6 space-y-4">
                                <div className="space-y-2">
                                    <Label htmlFor="ai-topic">What do you want to write about?</Label>
                                    <Textarea
                                        id="ai-topic"
                                        placeholder="e.g., How to prepare your car for long-distance rental in Nairobi"
                                        value={formData.topic}
                                        onChange={(e) => setFormData(prev => ({ ...prev, topic: e.target.value }))}
                                        className="min-h-[100px] border-2 rounded-2xl"
                                    />
                                </div>
                                <Button
                                    type="button"
                                    onClick={handleGenerate}
                                    disabled={isGenerating}
                                    className="w-full gap-2 rounded-xl h-12"
                                >
                                    {isGenerating ? (
                                        <>
                                            <Loader2 className="h-5 w-5 animate-spin" />
                                            Gemini is writing...
                                        </>
                                    ) : (
                                        <>
                                            <Sparkles className="h-5 w-5" />
                                            Generate Content with Gemini
                                        </>
                                    )}
                                </Button>
                            </CardContent>
                        </Card>

                        <div className="grid md:grid-cols-2 gap-8">
                            <Card className="rounded-3xl border-border/50">
                                <CardContent className="pt-6 space-y-4">
                                    <div className="space-y-2">
                                        <Label htmlFor="title">Blog Title</Label>
                                        <Input
                                            id="title"
                                            value={formData.title}
                                            onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
                                            required
                                            className="h-12 border-2 rounded-xl"
                                            placeholder="Enter a catchy title"
                                        />
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="category">Category</Label>
                                        <Select
                                            value={formData.category}
                                            onValueChange={(val) => setFormData(prev => ({ ...prev, category: val }))}
                                        >
                                            <SelectTrigger className="h-12 border-2 rounded-xl">
                                                <SelectValue placeholder="Select a category" />
                                            </SelectTrigger>
                                            <SelectContent>
                                                {categories.map(cat => (
                                                    <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                                                ))}
                                            </SelectContent>
                                        </Select>
                                    </div>
                                    <div className="space-y-2">
                                        <Label htmlFor="excerpt">Short Excerpt</Label>
                                        <Textarea
                                            id="excerpt"
                                            value={formData.excerpt}
                                            onChange={(e) => setFormData(prev => ({ ...prev, excerpt: e.target.value }))}
                                            className="min-h-[100px] border-2 rounded-xl"
                                            placeholder="A brief summary for the preview card"
                                        />
                                    </div>
                                </CardContent>
                            </Card>

                            <Card className="rounded-3xl border-border/50">
                                <CardContent className="pt-6 space-y-4">
                                    <div className="space-y-2">
                                        <Label htmlFor="cover">Cover Image URL</Label>
                                        <div className="flex gap-2">
                                            <Input
                                                id="cover"
                                                value={formData.cover_image}
                                                onChange={(e) => setFormData(prev => ({ ...prev, cover_image: e.target.value }))}
                                                className="h-12 border-2 rounded-xl"
                                            />
                                            <div className="h-12 w-12 rounded-xl bg-muted flex items-center justify-center shrink-0 overflow-hidden border-2">
                                                {formData.cover_image ? (
                                                    // eslint-disable-next-line @next/next/no-img-element
                                                    <img src={formData.cover_image} alt="Cover preview" className="object-cover h-full w-full" />
                                                ) : (
                                                    <ImageIcon className="text-muted-foreground h-6 w-6" />
                                                )}
                                            </div>
                                        </div>
                                    </div>
                                    <div className="p-4 rounded-2xl bg-primary/5 text-sm text-muted-foreground border border-primary/10">
                                        <p className="flex items-center gap-2 mb-2 font-bold text-primary">
                                            <CheckCircle2 className="h-4 w-4" />
                                            SEO Ready
                                        </p>
                                        <p>Publishing your post on Leli Rentals helps improve your brand visibility and helps others learn from your experience.</p>
                                    </div>
                                </CardContent>
                            </Card>
                        </div>

                        <Card className="rounded-3xl border-border/50">
                            <CardHeader>
                                <CardTitle>Content Body</CardTitle>
                                <CardDescription>Rich text is supported via HTML tags (h2, p, ul, li).</CardDescription>
                            </CardHeader>
                            <CardContent>
                                <Textarea
                                    id="content"
                                    value={formData.content}
                                    onChange={(e) => setFormData(prev => ({ ...prev, content: e.target.value }))}
                                    required
                                    className="min-h-[400px] border-2 rounded-2xl font-mono text-sm leading-relaxed"
                                    placeholder="Write your blog post content here..."
                                />
                            </CardContent>
                        </Card>

                        <div className="flex justify-end gap-4">
                            <Button type="button" variant="outline" onClick={() => router.back()} className="h-12 px-8 rounded-xl">
                                Cancel
                            </Button>
                            <Button type="submit" disabled={isLoading} className="h-12 px-12 rounded-xl font-bold text-lg">
                                {isLoading ? (
                                    <>
                                        <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                                        Publishing...
                                    </>
                                ) : (
                                    "Publish Post"
                                )}
                            </Button>
                        </div>
                    </form>
                </div>
            </main>
            <Footer />
        </div>
    )
}
